# Generated by Django 5.2.5 on 2025-08-18 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="email",
        ),
        migrations.AlterField(
            model_name="comment",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
